### ISSUE TITLE
尝试解密bin文件，程序报错，大佬能帮忙看看么

### ISSUE THREAD

**Issue by steamgirl2020** [hexstr/FGOAssetsModifyTool#1]
尝试解密最新日服bin文件，程序报错，大佬能帮忙看看么

Decrypt: Y:\r\Android\24d0fc396047b5ea450004e0aacc112fcc10761c.bin
Decrypt: Y:\r\Android\24d12337048dc4042a2d906f27cc4cbee1f4c4a2.bin
Decrypt: Y:\r\Android\24d616d3ba303d20173365746233354711011c11.bin
Decrypt: Y:\r\Android\24d83d4eb18c2c4c4986f343ea9fa7f86f5cc1ef.bin
Decrypt: Y:\r\Android\24df1474fdd83855933ba271a5c6ac48668ec714.bin
Decrypt: Y:\r\Android\24e24e430a5e5fb62a875587377250798d9dca64.bin
Decrypt: Y:\r\Android\24e351544782acd0508a16ceb5c2e062ceaff7d6.bin
Decrypt: Y:\r\Android\24e62b9d56872f85802244429c014df9cefd3a48.bin
Decrypt: Y:\r\Android\24f42d25dafd7cce5f9def0b0af6d1bb6a4ed287.bin
Decrypt: Y:\r\Android\24f569e2ab8d8dad162518253f3cd9db31a89129.bin
Decrypt: Y:\r\Android\24f59afbf77a65e4761f3024367c27751f2608d0.bin
Decrypt: Y:\r\Android\24fd1c3e0dc8a147c73f56b3023333b0cd97b7e2.bin
Decrypt: Y:\r\Android\24feeb3e4008b7a5614333dcc6062b2bb9e83160.bin
   在 System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   在 System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   在 System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   在 System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   在 System.IO.Stream.Close()
   在 System.IO.Stream.Dispose()
   在 CatAndMouseGame.DataDecryptor.Dispose(Boolean isDisposing)
   在 CatAndMouseGame.DataDecryptor.Dispose()
   在 CatAndMouseGame.MouseHomeMain(Byte[] data, Byte[] home, Byte[] info, Boolean isCompress)
MouseHomeMain failed
值不能为 null。
参数名: bytes
   在 System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   在 FGOAssetsModifyTool.Program.<DisplayMenuAsync>d__0.MoveNext()

**Comment by nishuoshenme** [comment]
抱歉现在才看到这个issue，不过我在文件夹里没找到`24feeb3e4008b7a5614333dcc6062b2bb9e83160.bin`这个文件所以没法复现，直接把这个文件删了重试吧。
