### ISSUE TITLE
我想要自己替换御主头像该如何做呢？

### ISSUE THREAD

**Issue by nokia10086** [hexstr/FGOAssetsModifyTool#10]
非常感谢您的分享，已star，想了解下我想要自己替换御主头像和立绘该怎么做呢？chara是如何打包的呢？

**Comment by hexstr** [comment]
@nokia10086 弄一张256x256的图片重命名为master.png放到Figure文件夹

**Comment by nokia10086** [comment]
@hexstr 好的，非常感谢！请问御主立绘也是同样操作吗？该怎么命名呢？

**Comment by hexstr** [comment]
这个要生成`Gudako_cover.png`和`Gudako_shadow.png`，我上传了`Gudako.psd`可以下载自己用ps改
