### ISSUE TITLE
如果是替换文件是不是理论IOS也能用

### ISSUE THREAD

**Issue by NepPure** [hexstr/FGOAssetsModifyTool#11]
不过可能需要越狱

或者 M1 M2芯片的MAC系统 安装ipa 资源也像是安卓一样就可以直接从目录访问替换了

**Comment by hexstr** [comment]
因为资源有crc校验所以要改一下代码bypass掉

**Comment by NepPure** [comment]
o(╥﹏╥)o 阿这 这个意思是 用这里解密加密好的资源直接替换也不行么 可能还需要修改主程序？

**Comment by hexstr** [comment]
@NepPure 是的

**Comment by NepPure** [comment]
刚刚搜了一下`zygisk` 大概明白了 安卓root过后 有这种类似的框架处理这些问题了 在这个基础上搞事情确实方便很多

不知道Ios有没有类似的东西

**Comment by hexstr** [comment]
@NepPure 非要说的话crc信息来自于AssetStorage.txt，或许可以劫持一下网络请求替换掉它，不过也要先bypass掉ssl证书校验才能抓包

**Comment by NepPure** [comment]
`AssetStorage.txt`主程序对这个的请求居然没有做加密？

全局代理安装自签发证书，这个都好办，这倒是个惊喜

**Comment by NepPure** [comment]
那这么说是不是安卓都不需要root了 通过代理的方式也能搞定文件替换这个问题

**Comment by hexstr** [comment]
@NepPure 前提是你能bypass掉证书校验

**Comment by hexstr** [comment]
@NepPure Android可以用模拟器，模块也支持

**Comment by NepPure** [comment]
_(:з」∠)_ 用的客户端内置证书吗 不是去信任系统通用根证书？

**Comment by hexstr** [comment]
@NepPure 日服反正不行，国服你要试试

**Comment by NepPure** [comment]
国服我觉得有戏

https://line1-patch-fate.bilibiligame.net/2450/NewResources/iPhone/AssetStorage.202208181824.txt

是通用证书 应该是认所有系统root证书的 我抽空去试一下

**Comment by NepPure** [comment]
然后关于这个文件的加解密应该可以参考大佬您的代码

**Comment by NepPure** [comment]
这个理论上不需要自定义 只是反和谐，大家应该可以通用？

**Comment by hexstr** [comment]
@NepPure 可以吧，不过iOS这种比较封闭的系统估计要越狱才能替换文件？

**Comment by NepPure** [comment]
是的 手机平板上是这样 

不过M1 M2芯片的MAC笔记本也能通关类似越狱的方式运行ios应用，所以在笔记本上玩就行了

**Comment by NepPure** [comment]
当然手机上还有个办法就是 把资源下载也代理了

**Comment by SekiBetu** [comment]
https://sekibetu.com/sniff01.html
证书和SSL Pinning都可以用magisk的模块和LSPosed的模块解决

**Comment by hexstr** [comment]
@SekiBetu 可以，但是OP在讨论如何无root使用

**Comment by NepPure** [comment]
[AssetStorage_dec.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/9437399/AssetStorage_dec.txt)

[AssetStorage.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/9437400/AssetStorage.txt)

大佬 我测试了一下 bgo ios 解密出来的文件 和实际文件名对不上

<img width="447" alt="image" src="https://user-images.githubusercontent.com/12379907/187017427-901bf18f-ead9-4147-9511-04d4cc684aa5.png">

有没有可能是ios的密钥还不一样？

**Comment by hexstr** [comment]
@NepPure 还真不太一样，神奇

**Comment by NepPure** [comment]
> @NepPure 还真不太一样，神奇

捂脸.jpg 大佬有空邦邦 超级感谢

**Comment by hexstr** [comment]
@NepPure 虽然但是我没有iOS设备ᖗ( ᐛ )ᖘ

**Comment by NepPure** [comment]
😭 有方法指路我自己去整一下也行

**Comment by hexstr** [comment]
@NepPure https://github.com/rayshift/translatefgo
这个翻译项目可以参考一下，直接修改AssetStorage绕过crc校验，你可以去看看代码

**Comment by NepPure** [comment]
好的 谢谢！

**Comment by NepPure** [comment]
这个文件的密钥ios也能用 要用客户端下面的 我一直用的Url里面的

**Comment by NepPure** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/12379907/187032631-4ea2c5a0-2699-47fd-973c-d62fdcecf685.png">

555 找了个安卓的对比 确实不一样 是不是应该放弃Ios了

**Comment by NepPure** [comment]
[9400480-黑杯.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9438080/9400480-.zip)

以黑杯为例，提供个ios和安卓的对比，等个有缘人 🙏🏻

**Comment by ACPudding** [comment]
我试了一下，是解密时候偏移量有微调。
用安卓那套解密key是对的，但是文件头是错的。
![QQ截图20220828140944](https://user-images.githubusercontent.com/22544986/187060306-dc509291-6c38-47f6-97bf-62b852d263d9.png)
问题出在MouseGame4

我试出来BGO的IOS是这样的:
`array[i] = (byte)(b2 ^ 205);
array[i + 1] = (byte)(b ^ 211);`

安卓是:
`array[i] = (byte)(b2 ^ 210);
array[i + 1] = (byte)(b ^ 206);`

**Comment by ACPudding** [comment]
> [9400480-黑杯.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9438080/9400480-.zip)
> 
> 以黑杯为例，提供个ios和安卓的对比，等个有缘人 🙏🏻

试了一下这个黑杯的包，也是改一下MouseGame4里面的偏移量就能成功读取了。
应该就是双端在MouseGame4里面的偏移量有区别。
![QQ截图20220828142416](https://user-images.githubusercontent.com/22544986/187060695-5dbf6f9d-6ece-4d69-a141-067c6ab9257c.png)

![QQ截图20220828142430](https://user-images.githubusercontent.com/22544986/187060700-32086ef1-c652-430b-b943-1d9e9c0d23ea.png)
