### ISSUE TITLE
模块在手机上没有工作

### ISSUE THREAD

**Issue by Silent-Oi** [hexstr/FGOAssetsModifyTool#12]
安装完模块后没有mod文件夹，自己新建一个文件夹后把42.char放入，进游戏没有变化。
请问可能是哪些原因呢？
![1BB334C520B39D6F336DEBDF061DE2F7](https://user-images.githubusercontent.com/112078238/186639102-9ca5d979-ca14-448f-bb87-d946b72d6584.jpg)
![2A84 28~8KRY~J(O04VI7EH](https://user-images.githubusercontent.com/112078238/186639333-b42c8543-69f0-40e2-b367-55827d149a02.png)
![D9E672C00CE75A2FE9092E7DDA2D7EE0](https://user-images.githubusercontent.com/112078238/186639122-bfd443a4-472a-49c5-8196-3a95e191ccad.jpg)

**Comment by hexstr** [comment]
@Silent-Oi 我就测试了模拟器专用的，手机版没测试，等更新吧

**Comment by hexstr** [comment]
测试了一下没问题，你用终端模拟器看看日志先
```shell
su
logcat -s hexstr:V
```

![Snipaste_2022-08-25_19-43-59](https://user-images.githubusercontent.com/28940831/186655709-82c49493-b96f-4405-8606-871e9f13a131.jpg)

**Comment by hexstr** [comment]
更新了0.2.1，可以先试试

**Comment by 1789984734** [comment]
大佬，请问你是用哪个模拟器，安卓几的，我雷电安卓九也和上面那个老哥一样

**Comment by hexstr** [comment]
@1789984734 雷电模拟器9.0.15，magisk版本24.1

**Comment by hexstr** [comment]
@1789984734 模拟器默安装的是32位，你要用adb覆盖安装

**Comment by 1789984734** [comment]
我用adb install -r --abi arm64-v8a FateGO.apk，会报错，说找不到arm64-v8a

**Comment by hexstr** [comment]
@1789984734 后面那个FateGO.apk你要换成你下载的文件名字

**Comment by 1789984734** [comment]
这个我知道

**Comment by 1789984734** [comment]
我把我的安装包改了

**Comment by 1789984734** [comment]
我又重新试了一下，报这个错误can't find 'arm64-v8a' to install

**Comment by hexstr** [comment]
@1789984734
![Snipaste_2022-08-25_20-19-10](https://user-images.githubusercontent.com/28940831/186662514-cee2960b-4ed7-4dc0-a8b6-574244689464.jpg)
应该没问题啊

**Comment by 1789984734** [comment]
![image](https://user-images.githubusercontent.com/66063123/186663026-6b0161ad-e60a-46d8-a8f6-f8daccd5f058.png)
我改成这样就能安装了，不知道和你那个一不一样

**Comment by hexstr** [comment]
@1789984734 你看看安装包里是不是没有lib\arm64文件夹了，没有就重新下载一个

**Comment by 1789984734** [comment]
![Uploading image.png…]()
只有这个。。。

**Comment by 1789984734** [comment]
只有这个。。。
![image](https://user-images.githubusercontent.com/66063123/186664738-64baea1f-388f-4fdf-a084-291a9f64639d.png)

**Comment by Silent-Oi** [comment]
![image](https://user-images.githubusercontent.com/112078238/186664639-4f1afd0e-a68c-41d2-a960-6c383247d7fc.png)
好像抓不到日志....

**Comment by hexstr** [comment]
@Silent-Oi 检查一下有没有arm64文件夹？

**Comment by Silent-Oi** [comment]
@hexstr 有的。
![L{ GA)SQS4NDD$2BYPSO_I3](https://user-images.githubusercontent.com/112078238/186666841-dde30d63-73d4-4297-b5f8-72c35b2af7c0.png)

**Comment by 1789984734** [comment]
@hexstr 换不了安装包，这个包有我想要的功能，看来鱼和熊掌不可兼得，先谢谢大佬回复了。

**Comment by Silent-Oi** [comment]
@hexstr 模块卸载重装之后好了，应该是我手机自己的问题。
感谢！
