### ISSUE TITLE
大佬没有生成Mod文件夹

### ISSUE THREAD

**Issue by nanachi0403** [hexstr/FGOAssetsModifyTool#14]
自己创建了一个之后按步骤把42放里面进游戏也没提示，黑杯还是只有卡背

**Comment by hexstr** [comment]
看看是不是64位，拉一份日志给我

**Comment by nanachi0403** [comment]
进去找到那个文件夹确实是arm64，但是日志本人太小白了不会拉...

**Comment by nanachi0403** [comment]
> 看看是不是64位，拉一份日志给我



> 看看不是64位，拉一份日志给我

进去找到那个文件夹确实是arm64，但是日志本人太小白了不会拉...

**Comment by hexstr** [comment]
下载终端模拟器，比如
https://m.apkpure.com/terminal-emulator/com.dmssoftwaresolutions.terminalemulator
```shell
su
logcat -s hexstr:V
```
一行一个回车，然后打开游戏，进游戏之后截图

**Comment by nanachi0403** [comment]
> 
![IMG_20220826_001935](https://user-images.githubusercontent.com/88043872/186718490-49d3ee5b-3b36-4edb-a428-95036d234c36.jpg)
大佬它蹦了两行就结束了，进入游戏也没有再继续刷，我寻思日志不应该是很长的玩意吗？我手机里还有另一个人的unityfpslocker模块解锁帧率用的，不知道和这个有没有关系？但是我试着删除也没有效果

**Comment by nanachi0403** [comment]
> @nanachi0403 你这没授予root权限啊
![IMG_20220826_003323](https://user-images.githubusercontent.com/88043872/186720869-d6aebc66-4705-4767-9e06-0f383866f9fc.jpg)
![IMG_20220826_003532](https://user-images.githubusercontent.com/88043872/186721096-5fcb3186-f71b-40a0-a86d-c173964315a1.jpg)
给了的呀，我这什么破手机

**Comment by hexstr** [comment]
root用户以#开头，不行就下载这个
https://f-droid.org/repo/com.dp.logcatapp_33.apk
下载后打开搜索`hexstr`

**Comment by hidskialf-hf** [comment]
大佬，模拟器v0.2.0的版本，从者的立绘还是重复的（我这目前看玉藻喵是这样的，），麻烦大佬方便的时候看下

**Comment by hexstr** [comment]
@hidskialf-hf 忘了这边，模拟器插件也更新了

**Comment by hidskialf-hf** [comment]
> @hidskialf-hf 忘了这边，模拟器插件也更新了

好勒，谢谢大佬

**Comment by hexstr** [comment]
模块没生效啊，你刷入了哪个文件？

**Comment by nanachi0403** [comment]
> 模块没生效啊，你刷入了哪个文件？
![IMG_20220826_003532](https://user-images.githubusercontent.com/88043872/186727148-47d974e7-071e-4af2-a7e3-026dc2479a93.jpg)
现在是0.22，0.10.2都试过累

**Comment by hexstr** [comment]
@nanachi0403 我没辙了

**Comment by hexstr** [comment]
@nanachi0403 哦对，还有一个magisk的遵守排除列表，看看在不在里面

**Comment by nanachi0403** [comment]
> @nanachi0403 我没辙了

大佬回我辛苦了，salute啊

**Comment by nanachi0403** [comment]
> > @nanachi0403 我没辙了
> 
> 大佬回我辛苦了，salute啊

我认了，

**Comment by Marxel-cn** [comment]
> > > @nanachi0403 我没辙了
> > 
> > 
> > 大佬回我辛苦了，salute啊
> 
> 我认了，

你得升级magisk，你这个应该还是24以前的版本（还有magiskhide），用的是zygote而不是zygisk
大佬能否做一个在zygote下也能用的版本……

**Comment by nanachi0403** [comment]
> > > > @nanachi0403 我没辙了
> > > 
> > > 
> > > 大佬回我辛苦了，salute啊
> > 
> > 
> > 我认了，
> 
> 你得升级magisk，你这个应该还是24以前的版本（还有magiskhide），用的是zygote而不是zygisk 大佬能否做一个在zygote下也能用的版本……
我用的是面具23.0，升级了一下果然可以用了，非常感谢，我是傻逼，浪费大伙这么长时间...
