### ISSUE TITLE
覆盖安装64位版本失败……

### ISSUE THREAD

**Issue by Wuliwalaking** [hexstr/FGOAssetsModifyTool#15]
使用 adb install -r --abi arm64-v8a .\FateGO.apk 进行覆盖安装后一直返回 can't find 'arm64-v8a' to install

**Comment by Kinomoyo** [comment]
一样，就卡在这步了，求大佬求求

**Comment by hexstr** [comment]
@Wuliwalaking @Kinomoyo 你们先检查一下安装包内有没有`lib\arm64`看看

**Comment by Wuliwalaking** [comment]
> 一样，就卡在这步了，求大佬救救 ![image](https://user-images.githubusercontent.com/112095956/186681922-36f6e539-bf73-442b-bf42-332cd72c6194.png)

是adb版本的问题好像，不可以用雷电自带的adb，我把mumu的adb复制过去就成功了

**Comment by Wuliwalaking** [comment]
> @Wuliwalaking @Kinomoyo 你们先检查一下安装包内有没有`lib\arm64`看看

谢谢大佬，好像是adb版本的问题，更换adb文件之后就安装成功了

**Comment by Kinomoyo** [comment]
> > 一样，就卡在这步了，求大佬救救 ![image](https://user-images.githubusercontent.com/112095956/186681922-36f6e539-bf73-442b-bf42-332cd72c6194.png)
> 
> 是adb版本的问题好像，不可以用雷电自带的adb，我把mumu的adb复制过去就成功了

大佬我替换后出现这个咋办
![image](https://user-images.githubusercontent.com/112095956/186700481-0be2e75b-d66e-44f4-bf67-832fd99481a1.png)

**Comment by Kinomoyo** [comment]
> > 一样，就卡在这步了，求大佬救救 ![image](https://user-images.githubusercontent.com/112095956/186681922-36f6e539-bf73-442b-bf42-332cd72c6194.png)
> 
> 是adb版本的问题好像，不可以用雷电自带的adb，我把mumu的adb复制过去就成功了

大佬我替换后出现这个咋办
![image](https://user-images.githubusercontent.com/112095956/186700684-d7d7c8f9-85ef-4e9a-8a17-1eb40a49a181.png)

**Comment by hexstr** [comment]
@Kinomoyo 字面意思，设备——也就是cpu不支持arm64架构的指令集

**Comment by Kinomoyo** [comment]
> @Kinomoyo 字面意思，设备——也就是cpu不支持arm64架构的指令集

有什么办法解决吗？难不成只能换电脑吗hhhhhh
