### ISSUE TITLE
大佬好，我是踩蘑菇FGO日服汉化组的组长

### ISSUE THREAD

**Issue by soulkey0117** [hexstr/FGOAssetsModifyTool#17]
[踩蘑菇FGO日服圈子](https://www.caimogu.cc/circle/380.html )  这个是我们汉化组发日服汉化的圈子，解包和打包FGO包的过程有很多问题，看到你在做BGO反和谐补丁，想联系大佬你帮忙看看。也想邀请你来踩蘑菇同步分享下你的反和谐补丁，造福被BGO折磨的社区玩家，不知道大佬可以加个联系方式不，我的微信：200990117

**Comment by hexstr** [comment]
虽然但是我不是BGO玩家，解包打包可以直接参考我这个repo的代码。

**Comment by soulkey0117** [comment]
没事啊，既然做出来了，在个BGO玩家集中的地方发挺好的呀

**Comment by soulkey0117** [comment]
哈哈，不是让你公布制作流程，就是发包让玩家下载，有的玩家上git费劲，git上下载回去也是在群里传播，不如你直接在踩蘑菇以作者身份发布，玩家知道你本人在发也会过来捧场

**Comment by hexstr** [comment]
没必要，总有人下载成功然后用国内云盘分流的

**Comment by BGO414** [comment]
虽然没看懂  谢谢爸爸们
