### ISSUE TITLE
mumu9装好之后，启动有小字弹出但是没有效果

### ISSUE THREAD

**Issue by STNBPK** [hexstr/FGOAssetsModifyTool#21]
![QQ图片20220826022319](https://user-images.githubusercontent.com/112117524/186740564-2823179d-0aa4-436b-acc2-cd0c05301753.png)
![QQ图片20220826022324](https://user-images.githubusercontent.com/112117524/186740581-f02faef1-b906-4d44-be60-a56ee51b59d0.png)
大佬能帮忙看下是哪里出问题了吗

**Comment by hexstr** [comment]
没有报错，模块也正常工作，看不出来

**Comment by STNBPK** [comment]
> 没有报错，模块也正常工作，看不出来

![QQ图片1](https://user-images.githubusercontent.com/112117524/186799346-4ee33a9c-6302-4b4d-93c0-2b2ce9f005bc.png)
我换了个模拟器后出现了这样的状况，大佬有解决办法吗

**Comment by hexstr** [comment]
在设置里面启用zygisk啊倒是

**Comment by STNBPK** [comment]
> 

启用了啊，assetreplace是正常运作的

**Comment by STNBPK** [comment]
> 在设置里面启用zygisk啊倒是

**Comment by STNBPK** [comment]
> 在设置里面启用zygisk啊倒是

![Uploading QQ图片20220826100942.png…]()

**Comment by STNBPK** [comment]
换了夜神就好了
