### ISSUE TITLE
请求再发布许可

### ISSUE THREAD

**Issue by NotAlwaysTrue** [hexstr/FGOAssetsModifyTool#27]
大佬我能在度盘转你的链接吗，然后附上比较详细的食用说明qwq

**Comment by hexstr** [comment]
@NotAlwaysTrue 可以的

**Comment by hidskialf-hf** [comment]
@hexstr 大佬，这几块的反和谐，您这能替换掉不，国服刚更新，人傻了
![Inked1](https://user-images.githubusercontent.com/112088504/186906771-05bfe980-1044-40a9-b0f4-3686d8173351.jpg)
![Inked3](https://user-images.githubusercontent.com/112088504/186906786-43a1bcf9-470b-4b88-85a3-287fb22b930f.jpg)
![2](https://user-images.githubusercontent.com/112088504/186906813-14c4e5e7-0330-4d23-a86c-253ab74f0984.jpg)

**Comment by hexstr** [comment]
@hidskialf-hf 这也太抽象了，我还以为是网友PS整的活

**Comment by NotAlwaysTrue** [comment]
是这样的啊，又有一堆人跑日服了==

**Comment by NotAlwaysTrue** [comment]
链接：https://pan.baidu.com/s/1d30uFBZnoFobyixwXfS_7Q?pwd=sssl 
提取码：sssl
没做完，在一点点加qwq

**Comment by siyige2727** [comment]
大佬们，真的是救命了
