### ISSUE TITLE
伪造libmain.so不能用在国服上吗

### ISSUE THREAD

**Issue by sayri23** [hexstr/FGOAssetsModifyTool#30]
rt

**Comment by hexstr** [comment]
以前有人和我说过BGO重新打包会有签名验证

**Comment by NotAlwaysTrue** [comment]
能
这个问题出在2b1b0ee6上
我发现问题实际上就是因为无法排除这个文件导致的
依靠伪造的文件启动时不能有这个文件，但是这个文件在每次启动都会生成
然后就gg

**Comment by NotAlwaysTrue** [comment]
@hexstr 能不能重写下目录让插件读取Mods而不是Mod
我试了很多次只要启动就会出现这个文件...

**Comment by hexstr** [comment]
@NotAlwaysTrue 不是有签名校验吗？你确定你重新签名了能用来玩游戏

**Comment by NotAlwaysTrue** [comment]
@hexstr 签名了，但是只要这个2b1存在这个就没法正常运行

**Comment by hexstr** [comment]
@NotAlwaysTrue 不，你直接重新签名什么文件都不改然后试试

**Comment by NotAlwaysTrue** [comment]
@hexstr 好的我去试一下

**Comment by NotAlwaysTrue** [comment]
只重签名的是完全正常的
修改文件后重签名是到登陆部分崩溃

**Comment by hexstr** [comment]
@NotAlwaysTrue 哦，看来是没有签名验证了啊

**Comment by NotAlwaysTrue** [comment]
@hexstr 他的签名验证似乎是只关于本地安装的问题
而且好像签名验证出错的那个是我(害怕)
那次我是没签名连logo都没弹出来

**Comment by hexstr** [comment]
@NotAlwaysTrue 实测过几秒会闪退，你可以试试只添加`libmain.so`进去

**Comment by NotAlwaysTrue** [comment]
@hexstr 测试了，完全不加载工具

**Comment by NotAlwaysTrue** [comment]
而且还是在老地方崩溃...

**Comment by luolikong1265446** [comment]
是不是不会崩溃的话 就可以弄出反和谐的客户端安装包
