### ISSUE TITLE
国服立绘替换png不生效

### ISSUE THREAD

**Issue by SkylineKID** [hexstr/FGOAssetsModifyTool#31]
您好，我使用的是雷电模拟器，确认64位，其他chara文件可以正常生效，根据步骤新建了立绘相关的文件夹，删除了custom.chara并另外使用了603700.png，也使用了enable相关的yaml文件，该png为窄边框psd替换二破卡面后快速导出的png，但是进游戏之后并没有效果，请问是什么原因，谢谢！

**Comment by hexstr** [comment]
哦，忘了更新文档，`Figure.yaml`要放在`Mod`文件夹，不是`Figure`文件夹

**Comment by SkylineKID** [comment]
再次尝试之后窄边框修改生效了，但是详情页面还是没有变化……另外有一个问题，您提供的PSD模板分别是只有前两破和前三破的，是否意味着如果要替换只能修改对应的状态呢？

**Comment by hexstr** [comment]
这也是代码更新文档滞后了，一二破在`id`后加`a`，三四破加`b`。窄边框不支持

**Comment by SkylineKID** [comment]
详情页文件夹下改成603700a.png后原本生效的窄边框也失效了……

**Comment by hexstr** [comment]
@SkylineKID

**Comment by SkylineKID** [comment]
我不懂代码这块所以完全是小白，sorry……确实不太明白要怎么搞

**Comment by NotAlwaysTrue** [comment]
@hexstr 大佬...要不你加下我qq我们处理下模拟器的问题...

**Comment by hexstr** [comment]
修好了，下载最新版
![Snipaste_2022-08-27_10-45-45](https://user-images.githubusercontent.com/28940831/187011285-0a568cc4-6515-474d-96e0-93191b45578b.jpg)

**Comment by SkylineKID** [comment]
更新两个zip并删除2b文件后，确认二破详情页面以及二破窄边框替换成功，但是详情页面选择满破时窄边框会变成1破

**Comment by hexstr** [comment]
@SkylineKID 窄边的就一张图，就是1破

**Comment by SkylineKID** [comment]
本来详情页选满破的话窄边也会对应满破图，删去详情页替换png后问题依然存在，我记得上一个版本好像不会这样……

**Comment by SkylineKID** [comment]
再次恢复到上一版本发现也是满破详情对应1破窄边 Orz 关于这点请问有没有什么办法可以解决呢

**Comment by hexstr** [comment]
@SkylineKID 无，因为我没写

**Comment by SkylineKID** [comment]
好的了解了，另外想问一下如果碰到需要卸载的大更新，卸载后全新安装，之后如果要再次进行素材替换的话后续要怎么操作？

**Comment by hexstr** [comment]
@SkylineKID 这要看游戏中的结构体变了没，变了模块就会失效。像日服这种万年不更新字段的可以一直用

**Comment by SkylineKID** [comment]
感谢！还有就是示范图例中兜帽艾蕾，请问这个是如何修改的？

**Comment by hexstr** [comment]
@SkylineKID 这是游戏自带的，我直接改了svtId

**Comment by SkylineKID** [comment]
那原版客户端要改svtld的话要进行哪些步骤？就比如您说的“新建figure文件夹blablabla”这种

**Comment by hexstr** [comment]
@SkylineKID 改代码

**Comment by SkylineKID** [comment]
所以主界面的从者立绘是没办法像替换详情页面立绘这样用png自定义替换的嘛

**Comment by hexstr** [comment]
@SkylineKID 可以啊，但我没想过有人会想替换立绘。一般都是在p站或者哪里看到一张图之后裁剪一下扔游戏里，立绘又不一样，还要自己抠图，也不一定有尺寸刚好的图拿来做

**Comment by SkylineKID** [comment]
好的了解了，我去解包看一下，感谢您的解答！

**Comment by 379490701** [comment]
真的是非常感谢大佬的辛苦付出，使用插件成功替换了格蕾的4个从者详情卡面（原卡面实在看不过去），不过窄边框的psd文件大佬只放了3套立绘模板，分别对应1 2 3破的从者详情页面立绘，如果我想修改 4套窄边框立绘 来对应1 2 3 4破的详情立绘，大佬觉得麻烦吗？麻烦就不要做了，真的再次衷心感谢大佬的付出！！赛高！！starstarstar！
