### ISSUE TITLE
半像和预览图能否实现替换

### ISSUE THREAD

**Issue by SLEEPIND** [hexstr/FGOAssetsModifyTool#32]
麻烦大佬加油，小白只能靠大佬了

**Comment by hexstr** [comment]
能，懒

**Comment by NotAlwaysTrue** [comment]
@hexstr 话说大佬用的什么模拟器啊。。。我试了3个模拟器用64位无论是修改apk还是安装后更改lib都是崩溃，只不过后改lib崩溃是进了界面，改apk是登陆崩溃
然后加了.chara之后无论如何都是在Logo处崩溃
求解qwq

**Comment by hexstr** [comment]
@NotAlwaysTrue Fate/GO Only

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/187906610-fae8fa7c-43d5-442d-bc70-4873154e96c8.png)

这是日服

![image](https://user-images.githubusercontent.com/12379907/187906636-721eb583-c4c8-4237-b39f-b4d85b3a80ad.png)

这是国服

如果纯粹从替换资源上来处理，每个版本更新都要重新P图 真的会烦死，如果有热心网游愿意维护这玩意，确实不是不能换

**Comment by NotAlwaysTrue** [comment]
确实很痛苦。。。如果写一个分类程序做更累（指调试）
