### ISSUE TITLE
大佬，我理了一份8.26和谐从者及礼装ID汇总，希望能对您有帮助

### ISSUE THREAD

**Issue by hidskialf-hf** [hexstr/FGOAssetsModifyTool#35]
大佬具体ID如下，希望大佬有空的时候方便看一下，看看能不能替换下

卡面立绘及从者详情页中半身像和谐：
斯卡哈（枪兵）ID:301300
大流士三世ID: 701100
咒腕哈桑ID:600200

概念礼装立绘及详情页中半身像和谐：
英灵肖像：斯卡哈 ID：9401020
不夜蔷薇 ID：9400410
街头巧克力女仆 ID：9401090
Go West!! ID：9401510
First Order ID：9301460
柔软的慈爱 ID：9401400
三色兼备 ID：9401560

从者及概念礼装详情页中半身像和谐：
俄里翁 ID：200900
卡米拉Assassin ID：601700
玉藻猫 ID：701600
美杜莎Rider ID：400100
牛若丸Rider ID：401400
剧院魅影 ID：601300

封印指定　执行者 ID：9400380
元素转换 ID：9400310
黑之圣杯 ID：9400480
卡姆兰之战 ID：9401700

队伍确认界面从者半身像和谐：
斯卡哈（枪兵）ID:301300
阿尔托莉雅·潘德拉贡〔Alter〕ID：100200
尼禄·新娘 ID：100600
牛若丸Rider ID：401400
美杜莎Rider ID：400100
剧院魅影 ID：601300

**Comment by hexstr** [comment]
可以，我就在等人整理

**Comment by hidskialf-hf** [comment]
> 可以，我就在等人整理

好勒，麻烦大佬啦

**Comment by beotconoar** [comment]
> 可以，我就在等人整理

大佬还有这位 102200 剑阶吉尔·德·雷 的第二张卡面
