### ISSUE TITLE
解包后替换了一下

### ISSUE THREAD

**Issue by qwerkilo** [hexstr/FGOAssetsModifyTool#36]
链接：https://pan.baidu.com/s/1b_X_UzT_xMpqkMOvHLDGLg?pwd=love 
提取码：love 
只替换了卡面，话说解包国服后找到了被和谐掉的资源，看了下有servants\status\301300下老太婆的头像，不知道能不能支持

**Comment by qwerkilo** [comment]
![image](https://user-images.githubusercontent.com/33748007/187020515-fd871f6c-20ba-4cc6-8267-3a065b7c9eb6.png)
mooncell上有头像，如果也能替换生效的话好多都可以恢复了

**Comment by hexstr** [comment]
#35

**Comment by SkylineKID** [comment]
> 链接：https://pan.baidu.com/s/1b_X_UzT_xMpqkMOvHLDGLg?pwd=love 提取码：love 只替换了卡面，话说解包国服后找到了被和谐掉的资源，看了下有servants\status\301300下老太婆的头像，不知道能不能支持

您好，麻烦能否发一下国服解包的所有文件？打包网盘ok，谢谢！

**Comment by qwerkilo** [comment]
> > 链接：https://pan.baidu.com/s/1b_X_UzT_xMpqkMOvHLDGLg?pwd=love 提取码：love 只替换了卡面，话说解包国服后找到了被和谐掉的资源，看了下有servants\status\301300下老太婆的头像，不知道能不能支持
> 
> 您好，麻烦能否发一下国服解包的所有文件？打包网盘ok，谢谢！
10几个G有点大，客户端下载完整包后用大佬的工具解密出所有bin，然后用AssetStudio可以导出图片，利用mooncell的图可以把被和谐的图片ps回去，然后用Figure挂回去就好了，工作量略大

**Comment by SkylineKID** [comment]
@qwerkilo 主要就是解密的步骤这里看不懂，网上去搜相关的教程也找不到模拟器的完整游戏包路径，所以才会想能不能有大佬帮忙QAQ

**Comment by qwerkilo** [comment]
> 

把d713中*.bin和*.bin.data混合的几万个文件直接拷贝入Android文件夹，并将其中名为“cfb1d36393fd67385e046b084b7cf7ed”的文件重命名为“AssetStorage.txt”
然后依次向程序输入指令：
6（解密目录）
5 （导出目录）
2 （解密所有文件）
即完成基本解密，使用AssetStudio打开Decrypted文件夹即可看到未加密文件

**Comment by hexstr** [comment]
@qwerkilo @SkylineKID 你们两个也不嫌麻烦，下载资源用这两个
https://github.com/ACPudding/Altera
https://github.com/ACPudding/Osakabehime

**Comment by SkylineKID** [comment]
@hexstr 哇 感谢！吃完饭研究一下先

**Comment by qwerkilo** [comment]
> @qwerkilo @SkylineKID 你们两个也不嫌麻烦，下载资源用这两个 https://github.com/ACPudding/Altera https://github.com/ACPudding/Osakabehime
原来有这个，我还解密搞了半天2333

**Comment by qwerkilo** [comment]
p了一下，应该都补齐了

**Comment by SkylineKID** [comment]
@hexstr 麻烦问下，Osakabehime下载日服资源现在显示进度到100%了依然有文件在下载，已经将近要下载了五六个小时了，请问这个是正常的情况吗？现在文件夹大概7.3G，是不是应该电脑开过夜让他下载了……

**Comment by hexstr** [comment]
@SkylineKID 直接去那个repo提issue去，我没用过不知道

**Comment by SkylineKID** [comment]
@hexstr 好的感谢！

**Comment by SkylineKID** [comment]
麻烦问下，半身像的替换要如何操作？我现在在Figure下新建了ServantsStatus的文件夹，png用301300-1命名，但是没有生效……

**Comment by qwerkilo** [comment]
> 

我的也没生效，应该还不行吧，我是按照Asset给的路径建的也不生效，如果生效的话就好了，礼装的话Asset里面也有，应该是可以替换掉bgo黑杯的大头的

**Comment by hexstr** [comment]
@SkylineKID 文档没写就是没有这功能

**Comment by SkylineKID** [comment]
好的吧了解，感谢！
