### ISSUE TITLE
昨晚还正常，今天起床所有版本都闪退

### ISSUE THREAD

**Issue by KAIN1994** [hexstr/FGOAssetsModifyTool#37]
请问是模拟器问题吗，大佬你测试用的是什么模拟器

具体表现是开游戏，卡在白色标志那个界面不动，下方有插件读取，然后就跟崩溃了一样闪退

重新打过插件，也覆盖了后面更新的chara

**Comment by KAIN1994** [comment]
忘说了我用的是夜神国际版7.0.3.3

**Comment by hexstr** [comment]
那就更新一下最新版，删掉`2b1b0ee6`文件

**Comment by NotAlwaysTrue** [comment]
@hexstr 最新版本报错崩溃原因是
08-27 16:34:30.712  6381  6431 E com.bilibili.fatego: terminating with uncaught exception of type std::__ndk1::ios_base::failure: ios_base::clear: unspecified iostream_category error
(IOS区服)
Mod文件夹存在非2b1b0ee6文件时会崩溃
只存在2b1b0ee6或为空时不崩溃
有什么头绪吗

**Comment by hexstr** [comment]
@NotAlwaysTrue 你干脆把`Mod`文件夹重命名为`Mod.bak`再试试

**Comment by NotAlwaysTrue** [comment]
@hexstr 不存在Mod文件夹时运行完全正常(我都把文件夹删了)

**Comment by NotAlwaysTrue** [comment]
然后我刷新了下文件列表，似乎每次启动都会创建2b1b0ee6这个文件

**Comment by KAIN1994** [comment]
> 

更新了，楼下的方法也试了...还是闪退，而且2b那个文件就昨天见过一次，今天没见过，甚至我刚才看了没产生日志

**Comment by NotAlwaysTrue** [comment]
@hexstr 我们好像碰上的是跟昨天晚上我整出来的问题是同一个问题。。。。。。

**Comment by NotAlwaysTrue** [comment]
我从官网上找了个新安装包整个模拟环境删掉重做还是这样....

**Comment by hexstr** [comment]
@NotAlwaysTrue 夜神啊，你把`adb`打开
```
adb shell
su
cat /proc/`pgrep fatego^Cmaps |grep libil2cpp.so
```

**Comment by NotAlwaysTrue** [comment]
75ac69e00000-75ac6cb42000 r--p 00000000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6cb42000-75ac6cb43000 rw-p 02d42000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6cb43000-75ac6cc14000 r--p 02d43000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6cc14000-75ac6cc15000 rw-p 02e14000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6cc15000-75ac6d44e000 r--p 02e15000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d44e000-75ac6d44f000 rw-p 0364e000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d44f000-75ac6d675000 r--p 0364f000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d675000-75ac6d676000 rw-p 03875000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d676000-75ac6d824000 r--p 03876000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d824000-75ac6d825000 rw-p 03a24000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d825000-75ac6d884000 r--p 03a25000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d884000-75ac6d885000 rw-p 03a84000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d885000-75ac6d8a8000 r--p 03a85000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d8a8000-75ac6d8a9000 rw-p 03aa8000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d8a9000-75ac6d8aa000 r--p 03aa9000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d8aa000-75ac6d8ab000 rw-p 03aaa000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d8ab000-75ac6d8b3000 r--p 03aab000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d8b3000-75ac6d8b4000 rw-p 03ab3000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6d8b4000-75ac6e85c000 r--p 03ab4000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6e86c000-75ac6f02d000 rw-p 04a5c000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6f30c000-75ac6f30d000 rw-p 0521c000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6f31c000-75ac6f322000 r--p 0521c000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
75ac6f331000-75ac6f3b3000 rw-p 05221000 08:13 5488695                    /data/app/com.bilibili.fatego-2SV_7X_M8UYDxxs4aRuXpA==/lib/arm64/libil2cpp.so
这个？

**Comment by hexstr** [comment]
@NotAlwaysTrue 嗯，以前写的时候专门给某个模拟器适配过代码，就是不记得是蓝叠还是夜神，看样子是夜神了

**Comment by hexstr** [comment]
@NotAlwaysTrue 建议换雷电9
https://cloud.189.cn/web/share?code=zmYnIzRVBrAn

**Comment by KAIN1994** [comment]
重启一下找到日志了
08-27 16:44:46.488  1550  1550 I : Magisk 25.2-delta(25200) daemon started
08-27 16:44:46.488  1550  1550 I : * Device API level: 28
08-27 16:44:46.499  1550  1552 I : ** post-fs-data mode running
08-27 16:44:46.499  1550  1552 E : opendir: /sys/fs/f2fs failed with 2: No such file or directory
08-27 16:44:46.499  1550  1552 E : write failed with 22: Invalid argument
08-27 16:44:46.499  1550  1552 I : node /sys/block/sdb/queue/discard_max_bytes tuned to 134217728
08-27 16:44:46.499  1550  1552 E : write failed with 22: Invalid argument
08-27 16:44:46.499  1550  1552 I : node /sys/block/sda/queue/discard_max_bytes tuned to 134217728
08-27 16:44:46.499  1550  1552 I : * Mounting mirrors
08-27 16:44:46.499  1550  1552 I : mount: /dev/0joIjRRM/.magisk/mirror/system
08-27 16:44:46.499  1550  1552 I : link: /dev/0joIjRRM/.magisk/mirror/cache
08-27 16:44:46.500  1550  1552 I : mount: /dev/0joIjRRM/.magisk/mirror/data
08-27 16:44:46.500  1550  1552 I : link: /dev/0joIjRRM/.magisk/mirror/vendor
08-27 16:44:46.500  1550  1552 I : link: /dev/0joIjRRM/.magisk/mirror/product
08-27 16:44:46.529  1550  1552 I : * Initializing Magisk environment
08-27 16:44:46.889  1550  1552 I : * Running post-fs-data.d scripts
08-27 16:44:46.893  1550  1552 E : open: /data/unencrypted/magisk_modules failed with 2: No such file or directory
08-27 16:44:46.893  1550  1552 I : * Running module post-fs-data scripts
08-27 16:44:46.902  1550  1552 I : * Loading modules
08-27 16:44:47.396  1550  1552 I : ** late_start service mode running
08-27 16:44:47.396  1550  1552 I : * Running service.d scripts
08-27 16:44:47.405  1550  1552 I : * Running module service scripts
08-27 16:44:48.590  1590  1590 I : zygisk32: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
08-27 16:44:48.590  1590  1590 I : zygisk32: replaced com/android/internal/os/Zygote#nativeForkSystemServer
08-27 16:44:48.763  1589  1589 I : zygisk64: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
08-27 16:44:48.763  1589  1589 I : zygisk64: replaced com/android/internal/os/Zygote#nativeForkSystemServer
08-27 16:44:49.987  1550  1552 I : hidelist: initializing internal data structures
08-27 16:45:03.081  2310  2310 I : zygisk64: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
08-27 16:45:03.081  2310  2310 I : zygisk64: replaced com/android/internal/os/Zygote#nativeForkSystemServer
08-27 16:45:03.428  1550  1552 I : ** boot-complete triggered
08-27 16:45:03.428  1550  1552 I : * Enable MagiskHide
08-27 16:45:03.435  1550  1552 I : hidelist add: [com.google.android.gms/com.google.android.gms.unstable]
08-27 16:45:03.445  1550  1552 I : hidelist add: [com.google.android.gms/com.google.android.gms]
08-27 16:45:03.446  1550  1552 I : hide: Reset sensitive props
08-27 16:45:15.458  4043  4043 I : zygisk64: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
08-27 16:45:15.458  4043  4043 I : zygisk64: replaced com/android/internal/os/Zygote#nativeForkSystemServer
总之我先去换雷电9试试吧

**Comment by NotAlwaysTrue** [comment]
头有点大，所以问题到底出在哪...qwq

**Comment by hexstr** [comment]
@NotAlwaysTrue @NotAlwaysTrue 一般这里只会输出四、五行。总之不换模拟器的话就我更新一下

**Comment by NotAlwaysTrue** [comment]
头大，开始改教程.jpg

**Comment by hexstr** [comment]
@KAIN1994 换雷电9的话magisk装完如果关闭root可能重启就没了，可以保持root开启。当然只是个人经验

**Comment by KAIN1994** [comment]
> @KAIN1994 换雷电9的话magisk装完如果关闭root可能重启就没了，可以保持root开启。当然只是个人经验

谢谢，知道了

**Comment by NotAlwaysTrue** [comment]
@hexstr 昨天晚上测了，关root直接magisk失效，所以可以实锤了

**Comment by NotAlwaysTrue** [comment]
@hexstr 雷电9相同问题
08-27 18:18:23.922  5772  5813 E com.bilibili.fatego: terminating with uncaught exception of type std::__ndk1::ios_base::failure: ios_base::clear: unspecified iostream_category error

**Comment by NotAlwaysTrue** [comment]
@hexstr 好像夜神也能用了
这个报错是我的锅，我4.chara忘记校验MD5了然后下下来一个0B的文件
我还在想为啥这个文件这么小T_T
