### ISSUE TITLE
请求翻译

### ISSUE THREAD

**Issue by hexstr** [hexstr/FGOAssetsModifyTool#38]
在[这个仓库](https://github.com/hexstr/FGOAssets)，需要把`mstSvt.yaml`中的从者名称修改正确，把`mstSvt-JP.yaml`新从者名称翻译并添加。

**Comment by hidskialf-hf** [comment]
mstSvt.yaml中的从者名称是要一个一个对过去，还是已经知道哪些从者名称有问题

**Comment by hexstr** [comment]
@hidskialf-hf 要修改bgo特色版，找找更新公告应该有。其它的不用管

**Comment by hidskialf-hf** [comment]
哦哦，例如：祖政修改回始皇帝这类是不

**Comment by hidskialf-hf** [comment]
> @hidskialf-hf 要修改bgo特色版，找找更新公告应该有。其它的不用管

@hexstr 我已经在找公告修改了，我能在里面直接修改，还是填在下面
<img width="992" alt="1" src="https://user-images.githubusercontent.com/112088504/187027422-def1f071-c4ee-4d90-a971-47f31eb6e872.PNG">

**Comment by hexstr** [comment]
@hidskialf-hf 可以，修改完提交我来合并

**Comment by hidskialf-hf** [comment]
> @hidskialf-hf 可以，修改完提交我来合并

@hexstr 已提交修改

**Comment by hexstr** [comment]
@hidskialf-hf 点一下Compare & pull request

**Comment by hexstr** [comment]
@hidskialf-hf 哦直接发这儿了啊

**Comment by hidskialf-hf** [comment]
@hexstr 现在可以了不，GitHub还在摸索怎么用，见谅

**Comment by hexstr** [comment]
@hidskialf-hf ok，合并了

**Comment by dts123d** [comment]
大佬们，点进去看了下还有两个杀生院的名字没有改，文档里还是暝生院祈荒，我是小白就不乱动了，提醒下你们

**Comment by w66936989** [comment]
我太笨了 日服不会弄

**Comment by SharpnelXu** [comment]
`mstSvt-JP.yaml`翻译已添加。PR: https://github.com/hexstr/FGOAssets/pull/6

**Comment by hexstr** [comment]
@SharpnelXu 辛苦啦，现在可以发布名称替换了

**Comment by w66936989** [comment]
[LocalizationJpn.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/9439197/LocalizationJpn.txt)
太难了上传和这里上传合并 一样吗 我也在摸索

**Comment by w66936989** [comment]
弄好了还在摸索
