### ISSUE TITLE
已完成mod文件夹操作，面具也挂好了，但是进入游戏未能显示模块在运作

### ISSUE THREAD

**Issue by EGOIST7** [hexstr/FGOAssetsModifyTool#39]

**Comment by EGOIST7** [comment]
![Uploading Screenshot_2022-08-27-17-31-49-405_com.vphonegaga.titan[1].jpg…]()
![Screenshot_2022-08-27-17-31-33-797_com vphonegaga titan 1](https://user-images.githubusercontent.com/112088263/187025009-bb42cbad-9059-40f5-9277-115abbb04d90.jpg)

**Comment by EGOIST7** [comment]
![Uploading Screenshot_2022-08-27-17-31-49-405_com.vphonegaga.titan[1].jpg…]()

**Comment by EGOIST7** [comment]
![Screenshot_2022-08-27-17-31-49-405_com vphonegaga titan 1](https://user-images.githubusercontent.com/112088263/187025081-ef0bd9ec-f383-4ac3-988d-e4b017efe91a.jpg)

**Comment by hexstr** [comment]
至少抓个日志
