### ISSUE TITLE
FGO2.56.1更新后无法解密

### ISSUE THREAD

**Issue by hexstr** [hexstr/FGOAssetsModifyTool#4]
看看有没有人贡献一下代码修复问题

**Comment by ACPudding** [comment]
日服部分资源用的key不是通用key。是为了防剧透设置的额外key（so里面我看过了是使用了
CatAndMouseGame.OtherHomeBuilding这个函数）
AssetStorage里面有小尾巴，这个是keytype。
![QQ截图20220703211941](https://user-images.githubusercontent.com/22544986/177041671-b0231c04-ced8-4271-a4aa-ec668e299627.png)
key的话存在topdata的assetbundlekey（用MasterDataUnpacker.MouseInfoMsgPack就能拆）
![QQ截图20220703212447](https://user-images.githubusercontent.com/22544986/177041811-9707242c-56aa-4032-84b0-f62d65346967.png)
解出来是这样的，可以对应解密keytype找key
![QQ截图20220703212057](https://user-images.githubusercontent.com/22544986/177041994-9257eca6-3285-41e4-997f-6984c55d27ae.png)
这是根据大佬您的已有内容加上的部分（瞎写的一个资源下载解密小工具orz），可以参考一下，mousegame3和mousegame4都是有针对防剧透设置的额外加密（写出来都很简单233，MouseGame3_34091232和 MouseGame4_34091820，OtherHomeBuilding也在里面orz）

[Osakabehime](https://github.com/ACPudding/Osakabehime/blob/master/CatAndMouseGame.cs)

**Comment by hexstr** [comment]
@ACPudding 感谢提供完整的思路和文件

**Comment by Thunderltx** [comment]
@ACPudding 感谢 感谢 不明觉厉

**Comment by ACPudding** [comment]
@hexstr 稍微补充一下 - -
剧情有用额外key加密的话是存在ScriptActionEncrypt@ScriptFileList.unity3d这个文件里面。MonoBehavior有对应文件的keytype
类似：
`"m_Name": "ScriptEncryptSetting",
  "settings": [
    {
      "scriptName": "9404650310",
      "keyType": "4239a5"
    },
    {
      "scriptName": "9404650311",
      "keyType": "4239a5"
    },......`
，当然图省事的办法就是暴力枚举((((((
不过暴力枚举只适合解密剧情文本的MouseGame3。（至少目前我试下来暂时没出问题orz.）
MouseGame4有多解可能，需要对应orz。

**Comment by hexstr** [comment]
@ACPudding 那改的还有点多，反正最近也没想提取的，干脆鸽了吧ᕕ( ᐛ )ᕗ
