### ISSUE TITLE
大佬，怎么改从者立绘上的名字啊

### ISSUE THREAD

**Issue by Sanctys** [hexstr/FGOAssetsModifyTool#40]
谢谢大佬最近的付出
大佬发的关于改立绘图片的方法学会了，也成功复现了，立绘上的名字是应该放哪个文件夹进行替换啊？

**Comment by hexstr** [comment]
还没更新文档

**Comment by 379490701** [comment]
真是纯纯为爱付出了，猛的一批大佬，我也是通过大佬的插件修改了部分从者的详情立绘，但是从者的职阶和名字用的还是迦摩的，或者直接我PS涂掉了，卡面上面就没有职阶和姓名了（捂脸.jpg）

**Comment by hexstr** [comment]
@379490701 下载对应的文件提取一下就行
https://github.com/ACPudding/Osakabehime
https://github.com/ACPudding/Altera

**Comment by 379490701** [comment]
@hexstr 强，这就去搞

**Comment by 379490701** [comment]
> @379490701 下载对应的文件提取一下就行 https://github.com/ACPudding/Osakabehime https://github.com/ACPudding/Altera

@hexstr 大佬，我用这俩工具对国服的资源文件解密，之后获取了一堆bin和unity3d文件，在json文件中找黑剑呆的id，
![image](https://user-images.githubusercontent.com/33148925/187057828-9e9a4dca-eeae-4b6a-9bf1-30798aa1d3dd.png)
网上搜了一下，还是不知道怎么从这些文件提取图片（捂脸.jpg）

**Comment by SkylineKID** [comment]
@379490701 https://github.com/Perfare/AssetStudio/releases/tag/v0.16.47

**Comment by 379490701** [comment]
> @379490701 https://github.com/Perfare/AssetStudio/releases/tag/v0.16.47

@SkylineKID 感谢感谢 这就去试试

**Comment by qwerkilo** [comment]
https://github.com/hexstr/FGOAssetsModifyTool/issues/35
我已经换好了，除了杰克的，日服资源名字是日文的话可以用国服解包的资源，卡面从mooncell拿然后ps就可以了

**Comment by 379490701** [comment]
@SkylineKID         hxd，从者详情满破卡面 对应 窄边框1破 的问题解决了吗（滑稽.jpg），我没解决，我看到国服资源解包下来，窄边框的文件有两个（<id>.png 和 <id>_2.png），
![image](https://user-images.githubusercontent.com/33148925/187064085-28658c48-033d-42e2-b429-94b9141642b5.png)
![image](https://user-images.githubusercontent.com/33148925/187064097-167453a8-c281-432f-bc4d-4538c9f6255d.png)
<id>.png负责前3个立绘，<id>_2.png负责满破立绘，但是我按照规则命名放置之后好像没用，满破显示的仍然是1破窄边框，我猜测大佬写的插件代码逻辑是满破窄边框读取的依旧是<id>.png而不是<id>_2.png，所以才会出现满破显示的仍然是1破窄边框

**Comment by 379490701** [comment]
@SkylineKID hxd，从者详情满破卡面 对应 窄边框1破 的问题解决了吗（滑稽.jpg），我没解决，我看到国服资源解包下来，窄边框的文件有两个（id.png 和 id_2.png），
![image](https://user-images.githubusercontent.com/33148925/187064215-1df21890-87f9-460a-9890-ced0c890c718.png)
![image](https://user-images.githubusercontent.com/33148925/187064223-1cc578a0-d38c-4b77-a0d9-f80cb006033e.png)
id.png负责前3个立绘，id_2.png负责满破立绘，但是我按照规则命名放置之后好像没用，满破显示的仍然是1破窄边框，我猜测大佬写的插件代码逻辑是满破窄边框读取的依旧是id.png而不是id_2.png，所以才会出现满破显示的仍然是1破窄边框

**Comment by Sanctys** [comment]
> #36 我已经换好了，除了杰克的，日服资源名字是日文的话可以用国服解包的资源，卡面从mooncell拿然后ps就可以了

别除了杰克啊大佬，解包卡面我有，教一下怎么改卡面名字吧，现在这晦气名字真的不想看见

**Comment by qwerkilo** [comment]
> > #36 我已经换好了，除了杰克的，日服资源名字是日文的话可以用国服解包的资源，卡面从mooncell拿然后ps就可以了
> 
> 别除了杰克啊大佬，解包卡面我有，教一下怎么改卡面名字吧，现在这晦气名字真的不想看见

名字不知道怎么改，我是直接用日服解包替换的，如果日服的解包卡面是日文我就用国服的卡面，从mooncell下载没被和谐的图片p掉已经被和谐的卡面。名字直接改的话除非有人做psd可以直接ps改，不然不知道怎么改，还有一个方法就是有和谐前国服的解包那直接替换就好了

**Comment by SkylineKID** [comment]
> 379490701
这个你得问作者了……
@hexstr

**Comment by qwerkilo** [comment]
贴吧有大佬p了杰克了，比较像了，我放到网盘了

**Comment by Sanctys** [comment]
感谢上面热心回复的大佬们，问题解决了，感谢感谢

**Comment by beotconoar** [comment]
> 贴吧有大佬p了杰克了，比较像了，我放到网盘了

杰克国服解包原图https://wwp.lanzouv.com/iLdTj0ai77wf

**Comment by qwerkilo** [comment]
> > 贴吧有大佬p了杰克了，比较像了，我放到网盘了
> 
> 杰克国服解包原图https://wwp.lanzouv.com/iLdTj0ai77wf

感谢！

**Comment by beotconoar** [comment]
> @beotconoar 借楼请教一下，其他国服和谐过的解包原图网上能找到么？搜了一下并没有找到，谢谢了。


我也不知道，只是我另一个模拟器上刚好有前一个版本的数据包没更新所以才幸存了
