### ISSUE TITLE
大佬，请问这个fgo asset replace模块只能用于B站服吗？

### ISSUE THREAD

**Issue by Agares002** [hexstr/FGOAssetsModifyTool#41]
b站服能正常运行，但渠道服模块不会运行，是两者客户端不太一样吗

**Comment by hexstr** [comment]
没测试，理论上FGO和BGO都能用

**Comment by Agares002** [comment]
好吧谢谢大佬，发现运行渠道服模块不会被触发:(

**Comment by hexstr** [comment]
@Agares002 模块会尝试注入包含`fategrandorder`或`fatego`的进程，渠道服包名不同吗？

**Comment by Agares002** [comment]
包名不一样，我的是 `com.bilibili.fgo.uc`
别的渠道服应该也是这个格式，可能还需要加入包含 `fgo`

**Comment by hexstr** [comment]
@Agares002 行吧我以后加上

**Comment by hexstr** [comment]
加上了
