### ISSUE TITLE
建议整理一下文档

### ISSUE THREAD

**Issue by oTnTh** [hexstr/FGOAssetsModifyTool#42]
目前文档分散在项目首页，以及ModuleDownload和AssetDownload的发布页面。既不方便找，也不方便改。

建议统一放到一个地方去，比如项目首页。

我找资料的时候写了个笔记，不嫌弃的话可以参考一下。

只是有些部分我也没找到答案，不然直接拿去用也可以的。

**Comment by oTnTh** [comment]
# FGOAssetsModifyTool

## 简介

一个适用于FGO日服及国服的MOD工具，主要功能有：

* 替换Master头像、立绘
* 替换从者立绘（头像框？指令卡？）
* 替换UI文本
* 替换剧情文本（汉化）
* 替换从者名称
* 替换从者说明文本

因为同时支持日服及国服，下述说明中凡是提及`[包名]`的部分，均可替换为以下二者其一：

* 日服：`com.aniplex.fategrandorder`
* 国服：`com.bilibili.fatego`

## 安装

大致分为程序本体和数据两个部分。

### 安装程序本体

[https://github.com/hexstr/FGOAssetsModifyTool/releases/tag/ModuleDownload]

（是不是直接提供一份`libFGOAssetReplace.so`好点）

（更新之后要手动删除Mod文件夹下的`2b1b0ee6`，为啥？）

#### Magisk

手机端：直接刷入`zygisk_FGOAssetReplace.zip`

模拟器端更复杂些：

* 先刷入`zygisk_X86PluginLoader.zip`
* 再刷入`zygisk_Plugin_FGOAssetReplace.zip`
* 将`TargetListEmulator.json`放置于`/data/local/tmp/TargetListEmulator.json`（为啥？）

因为本程序只支持`arm64-v8a`，模拟器可能需要覆盖安装：

`adb install -r --abi arm64-v8a FateGO.apk`

#### 修改APK并重新打包签名

* 下载`zygisk_Plugin_FGOAssetReplace.zip`并解压
* 下载`libmain.so`
* 在目录`gh@hexstr\FGOAssetReplace`得到`arm64-v8a.so`
* 重命名为`libFGOAssetReplace.so`之后，和`libmain.so`一起塞到`FateGO.apk/lib/arm64-v8a`目录下
* 最后使用MT管理器重新签名`FateGO.apk`并安装即可

#### 安装游戏后手工注入

如果有Root权限但是没有zygisk，或者能直接修改模拟器img文件的话：

* `libmain.so`
* `libFGOAssetReplace.so`

将上述文件手工放到`/data/app/[包名]/lib/arm64`也可以。

### 安装MOD数据

[https://github.com/hexstr/FGOAssetsModifyTool/releases/tag/AssetDownload]

相关内容需要放到下面两个目录之一（优先级？）：

* `/sdcard/Android/data/[包名]/files/Mod/`
* `/storage/emulated/0/Android/data/[包名]/files/Mod/`

## 自制MOD

（`0805.script`是啥，`*.chara`文件名是啥意思，从者名怎么改，等等）

**Comment by NotAlwaysTrue** [comment]
@oTnTh 国服的安装方式我整合过了
日服还在做(大汗)

**Comment by NotAlwaysTrue** [comment]
@oTnTh 
libmain.so
libFGOAssetReplace.so
这两个目前仅供Fate GO(非国服)

**Comment by oTnTh** [comment]
你是说安装游戏以后，手工注入libmain.so和libFGOAssetReplace.so的方式，并不适用于国服么？

这个也是应该加到文档里的。

我也觉得对于一般人而言，修改好的apk是个比较容易使用的方法，不过文档里还是尽可能包含多一点的技术细节比较好。

**Comment by liuyc84** [comment]
> 
国服要验证客户端，改不了

**Comment by oTnTh** [comment]
GitHub好像是有Wiki功能的，可不可以建议hexstr弄一下。
