### ISSUE TITLE
能否新增CharaFigure、Servants-Status的替换以及NarrowFigure的满破立绘功能

### ISSUE THREAD

**Issue by SkylineKID** [hexstr/FGOAssetsModifyTool#43]
根据解包得到了CharaFigure文件夹，应该是用于个人空间的从者立绘，举例来说的话想用礼服黑贞的figure替换3破状态；
另外解包NarrowFigure发现了一个从者对应两张png，第一张为1-3破第二张为满破，目前的插件只能替换第一张png，方便的话能否更新一下？谢谢！

**Comment by Archer-Tatsu** [comment]
想问下是解了大佬提供的.chara文件吗？正想问下这个文件是什么格式，该怎么打包，求赐教

**Comment by SkylineKID** [comment]
按照说明单独使用了枪师匠的301300_1立绘进行status替换，但是一破和二破都被替换成了301300_1，三破没有改变；
