### ISSUE TITLE
如何替换BGO包括幕间和主线在内的一众改名从者的剧情内容？

### ISSUE THREAD

**Issue by a08381** [hexstr/FGOAssetsModifyTool#50]
也是和日服一样使用[0805.script](https://github.com/hexstr/FGOAssetsModifyTool/releases/download/AssetDownload/0805.script)吗？

**Comment by hexstr** [comment]
@a08381 BGO?可以但没有必要

**Comment by a08381** [comment]
> @a08381 BGO?可以但没有必要

那么是有方法单独替换2.3的剧情内容和部分幕间物语的剧情内容的吗？

~~其实感觉大部分情况只需要替换一下对话框名字就行了~~

**Comment by hexstr** [comment]
@a08381 你以为script里的文本来自哪里(`ヮ´ )改不改有什么区别吗

**Comment by liuyc84** [comment]
2.3中国剧情，那些改名的中国从者太违和了

**Comment by Rakbow** [comment]
大佬想问问意思是指把0805.script文件加入mod文件夹就能替换被和谐的主线剧情文本了吗

**Comment by a08381** [comment]
> 大佬想问问意思是指把0805.script文件加入mod文件夹就能替换被和谐的主线剧情文本了吗

不行，这个0805.script本来就是从国服解包出来的，剧情文本和国服一模一样。

如果会自己打包的话只要手动替换一下2.3和2.4主线以及部分从者的幕间物语加上未来的淑女莱妮丝事件簿的文本就行了

不过我并不会打包
