### ISSUE TITLE
强化，好友等界面中选择的从者卡面的名字能替换吗？

### ISSUE THREAD

**Issue by beotconoar** [hexstr/FGOAssetsModifyTool#51]
自己用卡面替换时把下面的名字也一同替换了，在灵基一览中两者都正常替换，但是在强化界面选择她时卡面的名字又变回替换前，但此时卡面是替换后的状态，虽然是个小问题但还是很奇怪

**Comment by clria** [comment]
替换文本，用那个mstSvt.json改后缀名为yaml

**Comment by clria** [comment]
也许可以解决

**Comment by hexstr** [comment]
@beotconoar 看来是这几个场景加载了别的文件，暂时不会管

**Comment by beotconoar** [comment]
> 也许可以解决

卡面上的文字肯定是图片，文本是右上角那个

**Comment by beotconoar** [comment]
> 替换文本，用那个mstSvt.json改后缀名为yaml

卡面上的文字肯定是图片，文本是详情页右上角那个
