### ISSUE TITLE
国服和谐资源整理

### ISSUE THREAD

**Issue by clria** [hexstr/FGOAssetsModifyTool#56]
整理了大部分，放在了mod文件夹下
目前缺少国服和谐前的杨玉环、武则天、布狄卡、玛塔哈里和哪吒的立绘文件，不然中文名称就只能p图了
不知道如何在issue中上传文件，所以就贴百度云链接吧
链接：https://pan.baidu.com/s/1ZnJdBZc89LB4dvhmezEFjg 
提取码：elgl 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by clria** [comment]
效果图
![Uploading Screenshot_20220904_212211_com.vphonegaga.titan.jpg…]()
![Uploading Screenshot_20220904_212156_com.vphonegaga.titan.jpg…]()

**Comment by clria** [comment]
还有请问一下大佬这个assetreplacer是通过把文件加密后替换原本资源
还是注入代码来直接调用这些文件？
（因为status替换不了感觉好难受但是项目是闭源的所以只好自己从头写了hhh）

**Comment by hexstr** [comment]
@clria 直接替换

**Comment by clria** [comment]
> @clria 直接替换

ok感谢

**Comment by Leung36** [comment]
感谢分享，拿走了（请问有没有非官方交流群）

**Comment by Marisa-Shiriame** [comment]
靴靴

**Comment by liuyc84** [comment]
> 
大佬，可以去台服文件里找一找

**Comment by kamilosky** [comment]
询问大佬，在AssetModifyTool生成两json文件后，解密bin文件的返回的还是bin文件是不是不正常啊，使用的是最新一版的debug.zip

**Comment by sitorhy** [comment]
补充 哪吒 、布狄卡、玛塔哈丽、武则天、 项羽
[Figure.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9540823/Figure.zip)

**Comment by sitorhy** [comment]
日服搬过来的中华系 秦良玉 需要的凑合用
[Figure-JAP.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9540974/Figure-JAP.zip)

**Comment by sitorhy** [comment]
半身像
斯卡哈[Lancer]、大流士三世、咒腕哈桑、俄里翁、卡米拉[Assassin]、玉藻猫、美杜莎[Rider]、牛若丸[Rider]、剧院魅影
[Figure.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9546158/Figure.zip)

**Comment by zzxxccffcc** [comment]
9.1产生的bug：在刷9.1模块之前已经刷好了的卡面名，会在刷完模块之后变回修改前（就是国服改了的）的名字

**Comment by zzxxccffcc** [comment]
我不清楚是只有我这个出错了还是。。。

**Comment by zzxxccffcc** [comment]
@hexstr

**Comment by zzxxccffcc** [comment]
麻烦您了

**Comment by clria** [comment]
[Mod.z02.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9565894/Mod.z02.zip)
[Mod.z03.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9565935/Mod.z03.zip)
[Mod.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9565986/Mod.zip)
[Mod.z01.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9566000/Mod.z01.zip)
更新，感谢 @sitorhy

**Comment by clria** [comment]
> [Mod.z02.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9565894/Mod.z02.zip) [Mod.z03.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9565935/Mod.z03.zip) [Mod.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9565986/Mod.zip) [Mod.z01.zip](https://github.com/hexstr/FGOAssetsModifyTool/files/9566000/Mod.z01.zip) 更新，感谢 @sitorhy

把01 02 03 的zip后缀名去掉就行

**Comment by liuyc84** [comment]
感谢上面的大佬们，这就拿走试试

**Comment by zzxxccffcc** [comment]
问题已解决，刷完9.1包之后，要把mod包重新安。

**Comment by lxn1979** [comment]
> 整理了大部分，放在了mod文件夹下 目前缺少国服和谐前的杨玉环、武则天、布狄卡、玛塔哈里和哪吒的立绘文件，不然中文名称就只能p图了 不知道如何在issue中上传文件，所以就贴百度云链接吧 链接：https://pan.baidu.com/s/1ZnJdBZc89LB4dvhmezEFjg 提取码：elgl 复制这段内容后打开百度网盘手机App，操作更方便哦

请问如何更新？下载chara文件然后替换原来的就行了吗？
