### ISSUE TITLE
求救！日服卡死无响应

### ISSUE THREAD

**Issue by akalin777** [hexstr/FGOAssetsModifyTool#60]
今天日服更新后进入直接卡死在芙芙跑然后程序无响应，刚开始能正常运行几秒，然后就无响应了，把模块删除了就能正常进入，国服一切正常，求解决方法
![Screenshot_2022-09-07-19-33-00-356_com aniplex fategrandorder](https://user-images.githubusercontent.com/113027739/188868456-94ca3a84-d401-4bd2-90d0-c717fc9e65de.jpg)

**Comment by akalin777** [comment]
0.47的模块

**Comment by hexstr** [comment]
更新了
