### ISSUE TITLE
Plugin_0.5.0 模拟器失效

### ISSUE THREAD

**Issue by lzxqqqqq** [hexstr/FGOAssetsModifyTool#61]
更新后进入游戏有载入提示但是素材未替换
重新换回0.4.7版则重新生效

模拟器为NoxPlayerv7.0.3 安卓9

**Comment by hexstr** [comment]
无法复现

**Comment by qwerkilo** [comment]
0.5后bgo不生效，再入有提示，和lz一样情况

**Comment by hexstr** [comment]
@qwerkilo 用旧版

**Comment by zhaojianqing93** [comment]
> @qwerkilo 用旧版

没有找到旧版入口

**Comment by hexstr** [comment]
@zhaojianqing93 被我不小心删了，要不就等等我更新

**Comment by lzxqqqqq** [comment]
测试0.8.0版本模拟器也失败了，目前夜神模拟器能正常生效的最新的版本是0.6.0

**Comment by hexstr** [comment]
@lzxqqqqq 试试0.8.1

**Comment by lzxqqqqq** [comment]
> @lzxqqqqq 试试0.8.1

感谢，测试已修复。

**Comment by qwerkilo** [comment]
> @lzxqqqqq 试试0.8.1

0.8.1正常，大佬牛逼！三破也回来了，全都回来了！
