### ISSUE TITLE
似乎从0.5.0版本之后，国服（安卓B服）替换立绘失败……（上一次安装生效的版本是0.4.7）

### ISSUE THREAD

**Issue by 379490701** [hexstr/FGOAssetsModifyTool#63]
国服（安卓B服），安卓版本10，小米MIUI12。
反复测试之后，好像从某一个版本之后国服就替换失败了，从0.5.0版本到0.8.0版本，国服均不可用……
大佬的0.5.0版本更新日志上“新的寻址方式和新的版本号获取方式”，国服似乎出现了bug……
日志文件好像看不出来异常，第一张日志是功能正常版本，详情立绘替换成功。
![IWF91UZC((A96_L037RKHCI](https://user-images.githubusercontent.com/33148925/189348991-b61ee7dd-252f-4c62-a56a-f0880398b6ac.jpg)
第二张日志是失败版本，详情立绘替换失败……但是日志没有error……
![HBAVUQRKU(2%FK7FRJNHMXA](https://user-images.githubusercontent.com/33148925/189349189-a3c4de9f-cdce-40b9-9b45-cb75e9574abf.jpg)

**Comment by hexstr** [comment]
#61 更新`0.8.1`
