### ISSUE TITLE
0.81自定义CharaGraph丢失除满破外NarrowFigure

### ISSUE THREAD

**Issue by sitorhy** [hexstr/FGOAssetsModifyTool#66]
仅 400800a.png 400800b.png
没有 400800.png 400800_2.png
![Screenshot_20220910-233250](https://user-images.githubusercontent.com/20491546/189490884-9136fbae-e88c-4a94-8e20-444039b53066.png)

**Comment by hexstr** [comment]
忘记判断是否为空了，更新看看

**Comment by sitorhy** [comment]
正常了
