### ISSUE TITLE
除伽摩外的宝具名称替换完成了吗？

### ISSUE THREAD

**Issue by CountrySider** [hexstr/FGOAssetsModifyTool#68]
更新日志中提到“除部分从者（伽摩）外已替换了宝具名称和详情”，然而实测使用最新模块（0.9.1）后始皇帝的宝具名称仍是”祖政“。联想到预制文件中多出了几个最新的文件，请问是作者阁下遗漏还是需要使用某些新文件？

**Comment by hexstr** [comment]
[推荐下载](https://github.com/hexstr/FGOAssetsModifyTool/blob/module/docs/InstallationGuide.md#推荐下载)

**Comment by CountrySider** [comment]
原来是日服推荐下载那里。。。看到日服两字直接忽略了

**Comment by hexstr** [comment]
@CountrySider 我也没想到国服也需要这功能
