### ISSUE TITLE
0.9.1版本资料替换闪退

### ISSUE THREAD

**Issue by SEAYuch** [hexstr/FGOAssetsModifyTool#70]
夜神模拟器Android 9 64bits beta，使用mstSvtComment.yaml后点击资料闪退

**Comment by hexstr** [comment]
放个日志

**Comment by SEAYuch** [comment]
FATAL EXCEPTION: UnityMain
Process: com.bilibili.fatego, PID: 9051
java.lang.Error: signal 6 (SIGABRT), code -6 (?), fault addr --------
Build fingerprint: 'samsung/x1qzcx/x1q:9/QP1A.190711.020/900220715:user/release-keys'
Revision: '0'
pid: 9051, tid: 9081, name: UnityMain  >>> com.bilibili.fatego <<<
    x0   000000000000002d  x1   0000000000000001  x2   000000000000002d  x3   000077aba25b33c0
    x4   000000000b6a64c8  x5   000077ab035f55d0  x6   0000000000000000  x7   0000000000000030
    x8   000000000d6b58e0  x9   000000004d0b620e  x10  000000004d0b620e  x11  000000000000000d
    x12  000000000000000e  x13  000000000000000d  x14  000000000000006b  x15  0000000000000069
    x16  000077aafd324498  x17  000000000b905c40  x18  0000000000000001  x19  0000000000000000
    x20  000077ab035f6600  x21  000077aad5c20ca0  x22  0000000000000006  x23  000077aadaf7e0c0
    x24  0000000000000000  x25  000077aaed967140  x26  0000000000000000  x27  0000000000000001
    x28  0000000000000000  x29  000077ab035f6410  x30  000077aaf97a8374
    sp   000077ab035f6410  pc   000077aaf97a8374  pstate 0000000060000000
hexstr的没抓到
