### ISSUE TITLE
战斗界面半身像无法切换的问题

### ISSUE THREAD

**Issue by mcx1932446170** [hexstr/FGOAssetsModifyTool#72]
做好的三张自定义战斗半身像在灵基界面都可以显示，但在战斗界面始终是第二张自定义半身像，第三张和第一张无法生效

**Comment by mcx1932446170** [comment]
我替换掉的是宇宙凛的战斗半身像，三张图片命名分别为1100900_1; 1100900_2; 1100900_3。经过很多次实验，调整，基本可以确认为：当存在自定义战斗半身像时，无论其在什么位置，有且只有第二阶段的半身像可以使用，灵基界面使用一、三阶段半身像在战斗时会强制更换为第二阶段。求大大救救T.T

**Comment by mcx1932446170** [comment]
我大意了0.0，战斗界面半身像原来是和战斗模型绑定的吗？我再多试试

**Comment by hexstr** [comment]
这我还真不清楚，最后解决没

**Comment by mcx1932446170** [comment]
确定是战斗半身像跟随战斗模型了
