### ISSUE TITLE
关于IOS手机端的反和谐

### ISSUE THREAD

**Issue by kevinadol** [hexstr/FGOAssetsModifyTool#73]
大佬请问IOS手机端有没有办法可以实现反和谐（不使用模拟器）？

**Comment by NepPure** [comment]
#11 我已经实现了 自己签发个证书 拦截游戏请求 这种方案使用过于简单 不适合公开 你可以看我对这个仓库的fork 有关于ios文件的处理

**Comment by hexstr** [comment]
#11
