### ISSUE TITLE
2022年10月12日更新之后解密失败

### ISSUE THREAD

**Issue by 594hehe** [hexstr/FGOAssetsModifyTool#75]
按照操作解密出来的unity3D文件无法读取，尝试了AssetStudio，uTinyRipper，AssetBundleExtractor，结果全都报错或失败。

**Comment by hexstr** [comment]
@594hehe 给个不能解密的文件名

**Comment by 594hehe** [comment]
![QQ截图20221013094102](https://user-images.githubusercontent.com/78396797/195479241-0df21a22-5c47-4be9-abb6-4d931109f775.png)
![QQ截图20221013094241](https://user-images.githubusercontent.com/78396797/195479252-7db9a1fb-63c0-484f-9d33-1b1f494c8acd.png)
不是不能解密，是解密成功后的文件，尝试了很多软件都无法读取

**Comment by hexstr** [comment]
@594hehe 行，我中午试一下

**Comment by hexstr** [comment]
@594hehe 文件能解密成功，模型也没问题，换工具吧
![image](https://user-images.githubusercontent.com/28940831/195504897-ecf42716-cd0f-4375-b116-7878432c7ae0.png)

**Comment by 594hehe** [comment]
感谢，应该是我工具版本的问题了

**Comment by w66936989** [comment]
好家伙我都不会弄 哭
