### ISSUE TITLE
请问dailybonus可以支持bgo吗？

### ISSUE THREAD

**Issue by DAVIDZ2016** [hexstr/FGOAssetsModifyTool#76]
首先十分感谢大佬的反和谐和每日签到，十分感谢您。希望大佬可以开源下bgo的每日签到。因为在酷安也联系不上您，所以只能在这里issue发，如果引起你的不便的话提前说声抱歉

**Comment by hexstr** [comment]
![image](https://user-images.githubusercontent.com/28940831/196017599-bbfd88ae-1523-4357-af9f-1bb3cc5a5d41.png)

**Comment by DAVIDZ2016** [comment]
好吧，抱歉
