### ISSUE TITLE
模块在模拟器上无法工作

### ISSUE THREAD

**Issue by 215414** [hexstr/FGOAssetsModifyTool#9]
雷电模拟器9.0.13
magisk 24.1 开启zygisk 
![image](https://user-images.githubusercontent.com/51039191/184518136-fe983bf0-5bfe-4bef-87d8-f93d6457747b.png)
![image](https://user-images.githubusercontent.com/51039191/184518131-1c58c9f9-c958-41dc-bb08-434ece6a5836.png)
刷入模块后目录并没有生成Mod文件夹
新建Mod后存入文件
![image](https://user-images.githubusercontent.com/51039191/184518171-3f8ed3a9-3e54-4e90-94df-a019cc36f7be.png)
进入游戏，无变化，望告知解决方法，谢谢

**Comment by hexstr** [comment]
对，不支持模拟器

**Comment by 215414** [comment]
好吧，谢谢

**Comment by hexstr** [comment]
更新了，用[zygisk_FGOAssetReplace_v0.1_for_x86_only.zip](https://github.com/hexstr/FGOAssetsModifyTool/releases/download/Module_v0.1/zygisk_FGOAssetReplace_v0.1_for_x86_only.zip)

**Comment by Leung36** [comment]
> 

遇到相同问题 也是这个模拟器https://github.com/hexstr/FGOAssetsModifyTool/releases/download/Module_v0.1/zygisk_FGOAssetReplace_v0.1_for_x86_only.zip
这个链接已经下载不了了 求补

**Comment by hexstr** [comment]
@Leung36 https://github.com/hexstr/FGOAssetsModifyTool/releases/tag/Module

**Comment by Leung36** [comment]
> @Leung36 https://github.com/hexstr/FGOAssetsModifyTool/releases/tag/Module

谢谢 昨晚就是用的5天前更新的拆成两个的版本：zygisk_Plugin_FGOAssetReplace.zip、zygisk_X86PluginLoader.zip
我这里不生效TAT

**Comment by hexstr** [comment]
@Leung36 安装64位，直接安装都是32位的
`adb install -r --abi arm64-v8a FateGO.apk`

**Comment by Leung36** [comment]
> @Leung36 安装64位，直接安装都是32位的 `adb install -r --abi arm64-v8a FateGO.apk`

感谢 判断太准确了 
成功上车了

**Comment by hidskialf-hf** [comment]
> @Leung36安装64位，直接安装都是32位的 `adb install -r --abi arm64-v8a FateGO.apk`

您好，根据您的指示，国服客户端依然无法替换立绘，我截图给您，希望您的看下问题出在哪里
用的是mumu模拟器安卓9的版本，以及需要我这提供哪些具体的数据给您
<img width="1000" alt="面具1" src="https://user-images.githubusercontent.com/112088504/186667349-a9d8b4e0-cb25-49e1-8152-a17a0518ee84.png">
<img width="1000" alt="面具2" src="https://user-images.githubusercontent.com/112088504/186667365-0f8b9620-ae96-4b8e-babb-bece0c9922e3.png">
<img width="1000" alt="tmp" src="https://user-images.githubusercontent.com/112088504/186667376-e0465af8-7e44-4c34-88ad-78968129e6ff.png">
<img width="1000" alt="Mod" src="https://user-images.githubusercontent.com/112088504/186667391-29ac39c3-ee46-4a35-ad56-862b0877fde1.png">
<img width="1000" alt="64位" src="https://user-images.githubusercontent.com/112088504/186667427-c11ece54-46eb-4069-a96b-4a63c1050861.png">
