### ISSUE TITLE
大佬，我这里一次性把所有解密的bin扔进AssetStudio解密电脑就会卡死，想单独提取某个角色的语音和文本

### ISSUE THREAD

**Issue by nikoharo** [hexstr/FGOAssetsModifyTool#97]
我想提取謎の蘭丸X的语音和文本，大佬知道编号要怎么看吗

**Comment by nikoharo** [comment]
还有我这里解出来没有剧情文本。。

**Comment by hexstr** [comment]
https://apps.atlasacademy.io/db/JP/entities?name=%E8%AC%8E%E3%81%AE%E8%98%AD%E4%B8%B8X

**Comment by nikoharo** [comment]
> https://apps.atlasacademy.io/db/JP/entities?name=%E8%AC%8E%E3%81%AE%E8%98%AD%E4%B8%B8X

喔喔喔，感谢大佬的帮助

**Comment by hexstr** [comment]
音频在`AudioName.json`里面，文件名没有`bin`结尾

**Comment by nikoharo** [comment]
> 音频在`AudioName.json`里面，文件名没有`bin`结尾

啊？我从游戏那里下好的数据都是.bin或者就一串字符

**Comment by nikoharo** [comment]
![dsfdsfdsf](https://user-images.githubusercontent.com/96216203/218437343-7e96ebe0-c4a1-4b10-9f70-f2473de43790.png)

**Comment by hexstr** [comment]
哦，我是说文件名不带`bin`后缀的就是音频文件

**Comment by nikoharo** [comment]
> 音频在`AudioName.json`里面，文件名没有`bin`结尾。 自己搜索`CPK文件提取`

请问下AudioName.json文件在哪里呀。没找到

**Comment by hexstr** [comment]
@nikoharo 程序生成的`Android`目录下

**Comment by nikoharo** [comment]
![dsfdsffd](https://user-images.githubusercontent.com/96216203/218442273-8bb0ef4a-0d77-4e6c-8876-a0f9ce57b6fe.png)
我这里好像没有..

**Comment by nikoharo** [comment]
![asdssssd](https://user-images.githubusercontent.com/96216203/218442436-209cca55-737f-43ae-b7a6-ba1fb0cf54d9.png)
只有这两个json文件

**Comment by hexstr** [comment]
菜单中的`6: 解析AssetStorage.txt`就是啊，没有生成吗

**Comment by nikoharo** [comment]
> 菜单中的`6: 解析AssetStorage.txt`就是啊，没有生成吗

哦哦找到了，好像是因为之前删文件误删了，重新生成了一下有了.请问下角色文本要怎么提取，我这里搜了一下好像没有script开头的.bin文件
![asdasd](https://user-images.githubusercontent.com/96216203/218450603-8042cefd-68ba-4a89-8126-4c4073f520ee.png)

**Comment by hexstr** [comment]
在`AssetName.json`里找到包含`Script`的文件名，把这些文件放到`Android\Scripts`下，然后在菜单中用`10: 解密剧情文本(scripts)`

**Comment by nikoharo** [comment]
> 在`AssetName.json`里找到包含`Script`的文件名，把这些文件放到`Android\Scripts`下，然后在菜单中用`10: 解密剧情文本(scripts)` 哦这个是剧情文本，如果你要的是召唤台词什么的，先使用`8: 解析Master`然后找`Android\gamedata\unpack_master\mstSvtVoice`

感谢帮助，请问下强化时的台词在哪里找啊

**Comment by hexstr** [comment]
@nikoharo 我不到啊

**Comment by nikoharo** [comment]
> 

啊，好吧

**Comment by nikoharo** [comment]
![assssasd](https://user-images.githubusercontent.com/96216203/218466178-94fe5ca9-b7b1-4ceb-9c1f-8fb0d1fbe5c8.png)
这种语音对应的台词要怎么找哇，其实我想拿来练vits

**Comment by hexstr** [comment]
@nikoharo https://github.com/ACPudding/Altera
看看这个项目？

**Comment by nikoharo** [comment]
> @nikoharo https://github.com/ACPudding/Altera 看看这个项目？

!我试试

**Comment by nikoharo** [comment]
我解密剧情剧情文本好像没有啊
![ssssadsd](https://user-images.githubusercontent.com/96216203/218473113-91a254af-715b-485e-a71a-592b217f7269.png)

**Comment by hexstr** [comment]
太久没用我都忘记用法了。
首先要在·AssetName.json·里找到包含·Script·的文件名，把这些文件放到`Android`文件夹下解密，然后把解密后的文件用`AssetStudio`打开，提取所有的txt，每个文件提取出来的txt应该会放在同一个文件夹，然后把这些文件夹扔到`Android\Scripts`，最后才是`10: 解密剧情文本(scripts)`

**Comment by hexstr** [comment]
还有提取的是日服吗？

**Comment by nikoharo** [comment]
> 还有提取的是日服吗？

是的

**Comment by hexstr** [comment]
BGO为了汉化我倒是写了一键提取的工具，FGO没有233

**Comment by nikoharo** [comment]
> BGO为了汉化我倒是写了一键提取的工具，FGO没有233

一键提取剧情文本？是哪个能让我康康吗

**Comment by nikoharo** [comment]
那两个项目我都用了，感觉跟hexstr写的这个FGOAssetsModifyTool都差不多，有没有像https://github.com/chinosk6/umamusume-voice-text-extractor这种项目一样的，直接可以提取角色对应的语音和文本，一个个去翻太麻烦了

**Comment by hexstr** [comment]
我目前没见到过

**Comment by nikoharo** [comment]
> 我目前没见到过

哦哦，感谢hexstr sama的帮助，感激不尽

**Comment by nikoharo** [comment]
> 在`AssetName.json`里找到包含`Script`的文件名，把这些文件放到`Android\Scripts`下，然后在菜单中用`10: 解密剧情文本(scripts)` 哦这个是剧情文本，如果你要的是召唤台词什么的，先使用`8: 解析Master`然后找`Android\gamedata\unpack_master\mstSvtVoice`

话说怎么找謎の蘭丸X那段剧情文本啊

**Comment by hexstr** [comment]
@nikoharo 不知道，我只写工具但不怎么分析

**Comment by nikoharo** [comment]
> @nikoharo 不知道，我只写工具但不怎么分析

哦哦我知道了，如果hexstr sama不介意的话，还有其他联系方式吗，比如说群聊什么的

**Comment by hexstr** [comment]
@nikoharo http://t.me/fuckuimnotabot
